---
title: "Eindopdracht"
author: "Mitchel Eilerts en Lucas Mooij"
date: "2024-12-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(fpp3)
library(ggplot2)
library(ggrepel)

```






```{r}
#filepaden voor Mitchel
files <- read.csv("C:\\Users\\mitch\\OneDrive\\Documenten\\Studie Toegepaste wiskunde\\Tijdreeksen\\datasets\\datasets\\filedata.csv", sep = ";")

weer_data <- read.csv("C:\\Users\\mitch\\OneDrive\\Documenten\\Studie Toegepaste wiskunde\\Tijdreeksen\\datasets\\datasets\\weer.csv", sep = ";")

```





```{r}
#filepaden voor Lucas





```


```{r}
file_data



```


```{r}
weer_data


```


```{r}
files$zwaarteKmMin <- as.numeric(files$zwaarteKmMin)
files$BeginDatum <- as.Date(files$BeginDatum)
filedag <- aggregate(zwaarteKmMin ~ BeginDatum, data = files, FUN = sum)
alle_datums <- data.frame(BeginDatum = seq(min(as.Date(files$BeginDatum)), 
                                           max(as.Date(files$BeginDatum)), 
                                           by = "day"))
filedag <- merge(alle_datums, filedag, by = "BeginDatum", all.x = TRUE)
filedag$zwaarteKmMin[is.na(filedag$zwaarteKmMin)] <- 0
colnames(filedag) <- c("Datum", "Zwaarte")







```


```{r fig.width=80, fig.height=6}
filedag %>%
  autoplot(Zwaarte) +
  labs(
    title = "Totale filelengte per dag",
    x = "Jaar",
    y = "Filelengte"
  )

```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


