---
title: "Eindopdracht"
author: "Mitchel Eilerts en Lucas Mooij"
date: "2024-12-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(fpp3)
library(ggplot2)
library(ggrepel)

```






```{r}
file_data <- read.csv("C:\\Users\\mitch\\OneDrive\\Documenten\\Studie Toegepaste wiskunde\\Tijdreeksen\\datasets\\datasets\\filedata.csv", sep = ";")

weer_data <- read.csv("C:\\Users\\mitch\\OneDrive\\Documenten\\Studie Toegepaste wiskunde\\Tijdreeksen\\datasets\\datasets\\weer.csv", sep = ";")

```





```{r}



```


```{r}
file_data



```


```{r}
weer_data


```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


```{r}




```


